### ISSUE TITLE
New logo for Django Easy SEO

### ISSUE THREAD

**Issue by familqasimov** [bashu/django-easy-seo#8]
Hi sir. I'm graphic designer.I have studied your work and I think a new design will make you more visible. I would like to offer you logo. I can give you all the formats of the design free. If you want a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/39088486-029d1aca-45c4-11e8-8859-c88ed6898c51.png)

**Comment by bashu** [comment]
![36909043-e1f2c704-1e34-11e8-84d7-b3119091cb2c](https://user-images.githubusercontent.com/144783/39091576-6eb389ea-4620-11e8-841e-d751aff55b63.gif)

@familqasimov 👍

**Comment by bashu** [comment]
@familqasimov show me sources open and send PR

**Comment by familqasimov** [comment]
I'm glad you like it. I sent you logo link. https://drive.google.com/drive/folders/1t3iDk0b12asKOfJFo03H6Fo0IqGpvuL2
If you want a change please specify.

**Comment by familqasimov** [comment]
Did you like this logo?

**Comment by bashu** [comment]
@familqasimov project is dead, but here you go https://github.com/bashu/django-easy-seo

**Comment by familqasimov** [comment]
Why my friend?

29 apr 2018, Baz 09:25 tarixində Basil Shubin <notifications@github.com>
yazdı:

**Comment by bashu** [comment]
@familqasimov inactive for 3 years, because not needed anymore. Anyway thanks for the logo, feel free to add yourself in AUTHORS.rst

**Comment by familqasimov** [comment]
Very thanks. I wish good luck everyone everywhere... 👍

29 apr 2018, Baz 09:33 tarixində Basil Shubin <notifications@github.com>
yazdı:
